//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 04:36:09 PM CEST 
//


package com.telekomsrbija.ws.crm.wsfaults;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.telekomsrbija.ws.crm.wsfaults package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Fault_QNAME = new QName("http://www.telekomsrbija.com/ws/crm/WSFaults", "Fault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.telekomsrbija.ws.crm.wsfaults
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenericFaultType }
     * 
     */
    public GenericFaultType createGenericFaultType() {
        return new GenericFaultType();
    }

    /**
     * Create an instance of {@link FaultMessagesType }
     * 
     */
    public FaultMessagesType createFaultMessagesType() {
        return new FaultMessagesType();
    }

    /**
     * Create an instance of {@link FaultParametersType }
     * 
     */
    public FaultParametersType createFaultParametersType() {
        return new FaultParametersType();
    }

    /**
     * Create an instance of {@link FaultMessage }
     * 
     */
    public FaultMessage createFaultMessage() {
        return new FaultMessage();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.telekomsrbija.com/ws/crm/WSFaults", name = "Fault")
    public JAXBElement<GenericFaultType> createFault(GenericFaultType value) {
        return new JAXBElement<GenericFaultType>(_Fault_QNAME, GenericFaultType.class, null, value);
    }

}
