//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.21 at 04:36:09 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.telekomsrbija.com/ws/crm/WSFaults")
package com.telekomsrbija.ws.crm.wsfaults;
