//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.27 at 09:25:15 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sargije.com/ws/common", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sargije.ws.common;
