//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.27 at 09:25:15 AM CET 
//


package com.sargije.ws.wsfaults;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GenericFaultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenericFaultType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FaultCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FaultMessages" type="{http://www.sargije.com/ws/wsfaults}FaultMessagesType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericFaultType", propOrder = {
    "faultCode",
    "faultMessages"
})
public class GenericFaultType {

    @XmlElement(name = "FaultCode", required = true)
    protected String faultCode;
    @XmlElement(name = "FaultMessages", required = true)
    protected FaultMessagesType faultMessages;

    /**
     * Gets the value of the faultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaultCode() {
        return faultCode;
    }

    /**
     * Sets the value of the faultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaultCode(String value) {
        this.faultCode = value;
    }

    /**
     * Gets the value of the faultMessages property.
     * 
     * @return
     *     possible object is
     *     {@link FaultMessagesType }
     *     
     */
    public FaultMessagesType getFaultMessages() {
        return faultMessages;
    }

    /**
     * Sets the value of the faultMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link FaultMessagesType }
     *     
     */
    public void setFaultMessages(FaultMessagesType value) {
        this.faultMessages = value;
    }

}
